[tool.poetry]
name = "mass-composition"
version = "0.1.0"
description = ""
authors = ["Greg <greg@elphick.com.au>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
xarray = "^2022.6.0"
periodictable = "^1.6.1"
matplotlib = { version = "^3.6.2", optional = true }
plotly = { version = "^5.10.0", optional = true }
kaleido = { version = "0.2.1", optional = true }
networkx = { version = "^2.8.8", optional = true }

[tool.poetry.extras]
viz = ["matplotlib", "plotly", "kaleido"]
flowsheet = ["networkx"]

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
Sphinx = "^5.0.2"
sphinx-rtd-theme = "^1.0.0"
sphinx-gallery = "^0.11.1"
sphinx-autodoc-typehints = "^1.18.3"
myst-parser = "^0.18.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
