[tool.poetry]
name = "xr-mass-composition"
version = "0.1.0"
description = ""
authors = ["Greg <greg@elphick.com.au>"]

[tool.poetry.dependencies]
python = "^3.8"
xarray = "^2022.6.0"
periodictable = "^1.6.1"
matplotlib = "^3.6.0"
plotly = "^5.10.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
Sphinx = "^5.0.2"
sphinx-rtd-theme = "^1.0.0"
sphinx-gallery = "^0.10.1"
sphinx-autodoc-typehints = "^1.18.3"
myst-parser = "^0.18.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
