[tool.poetry]
name = "mass-composition"
version = "0.1.6"
description = ""
authors = ["Greg <greg@elphick.com.au>"]
packages = [{include = "elphick/mc/mass_composition"}]

[[tool.poetry.source]]
name = "pypi_elphick"
url = "http://192.168.0.110:8080"
secondary = false

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
xarray = "^2022.6.0"
periodictable = "^1.6.1"
matplotlib = { version = "^3.6.2", optional = true }
plotly = { version = "^5.13.0", optional = true }
kaleido = { version = "0.2.1", optional = true }
networkx = { version = "^3.0.0", optional = true }
seaborn = { version = "^0.12.2", optional = true }
pyyaml = "^6.0"
scipy = "^1.10.0"
pyvista = "^0.37.0"
pyvista-xarray = "^0.1.2"
coverage = "^7.0.5"
notebook = "^6.5.2"

[tool.poetry.extras]
viz = ["matplotlib", "seaborn", "plotly", "kaleido"]

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
Sphinx = "^5.0.2"
sphinx-rtd-theme = "^1.0.0"
sphinx-gallery = "^0.11.1"
sphinx-autodoc-typehints = "^1.18.3"
myst-parser = "^0.18.0"
#notebook = "^8.8.0"

[tool.poetry.group.dev.dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
