name: "Docs Check"
on:
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: install dependencies
      run: |
        pip install sphinx-rtd-theme
        pip install sphinx-gallery
        pip install sphinx-autodoc-typehints
        pip install myst-parser
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
