name: "Check Docs"
on:
   push:
     paths:
       - 'examples/*.py'
       - 'docs/**'

jobs:
  check_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        pip install mass-composition -e ".[viz,network,omf]"
        pip install sphinx sphinx_rtd_theme
        pip install sphinx-gallery
        pip install sphinx-autodoc-typehints
        pip install myst-parser
        pip install orca
        pip install pytest
    - name: Sphinx build
      run: |
        sphinx-build docs/source _build
        
