name: "Check Docs"
on:
  push:
    paths:
      - 'docs/**'

jobs:
  check_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        pip install mass-composition
        pip install sphinx sphinx_rtd_theme
        pip install sphinx-gallery
        pip install sphinx-autodoc-typehints
        pip install myst-parser
        pip install orca
        pip install plotly
        pip install matplotlib
        pip install pytest
        pip install kaleido
    - name: Sphinx build
      run: |
        sphinx-build docs/source _build
